### ISSUE TITLE
A question about one "OPTION" in your shell scripts

### ISSUE THREAD

**Issue by dlagul** [takuhirok/NR-GAN#1]
# Set up model
case ${MODEL} in
    "gan" ) ;;
    "ambientgan" )
    OPTION="${OPTION} --noise_measure" ;;
    "sinrgan1" )
    OPTION="${OPTION} --prior additive_gaussian" ;;
    "sinrgan2" )
    OPTION="${OPTION} --gn_train --rotation --channel_shuffle --color_inversion" ;;
    "sdnrgan1" )
    OPTION="${OPTION} --gn_train --prior ${PRIOR}" ;;
    "sdnrgan2" )
    OPTION="${OPTION} --gn_train --implicit --prior additive_gaussian" ;;
    "sdnrgan3" )
    OPTION="${OPTION} --gn_train --implicit --color_inversion" ;;
    * )
    echo "unknown MODEL: ${MODEL}"
    exit 1 ;;
esac

I read your paper, an excellent work which inspires me a lot. However, when I view your source code, I have a question about one "OPTION" in your shell scripts. 
As shown above, in the case of "sinrgan1", OPTION="${OPTION} --prior additive_gaussian". Refer to you paper, in the case of "SI-NR-GAN-I", do I need to add "--gn_train" to this option, i.e., OPTION="${OPTION} --gn_train --prior additive_gaussian", to train a "netGn" ? I am not sure here,  maybe I missed some details. If there is no need to add anything here, could you please explain why.
Your kind reply will help me understand your work well. Thanks a lot.

**Comment by takuhirok** [comment]
Hi, @dlagul 
Thank you for pointing it out. It seems that I have deleted "--gn_train" by mistake when I cleaned up the code. As you indicated, "--gn_train" should be used in the case of "sinrgan1." I have corrected the code now. So, please check out the latest version.

**Comment by dlagul** [comment]
Hi author, thanks for your kind reply.
Best regards.
